name: ARGOCD

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: false
        type: string
      APP_ENV:
        required: true
        type: string
      ARGOCD_CONF_DIR:
        required: false
        type: string
        default: .argocd
      APP_PROJ_FILE_ARGOCD:
        required: false
        type: string
        default: project.yaml
      APP_FILE_ARGOCD:
        required: false
        type: string
        default: application.yaml
      DOCKER_TAG_SUFFIX:
        required: false
        type: string
        default: ""
      DEPLOY_TYPE:
        required: false
        type: string
        default: "kustomize"
    secrets:
      GH_TOKEN:
        required: true
      ARGOCD_USER:
        required: true
      ARGOCD_PASS:
        required: true
      ARGOCD_URL:
        required: true

env:
  APP_ENV: "${{ inputs.APP_ENV }}"
  APP_NAME: "${{ inputs.APP_NAME }}"
  APP_PROJ_FILE_ARGOCD: "${{ inputs.APP_PROJ_FILE_ARGOCD }}"
  APP_FILE_ARGOCD: "${{ inputs.APP_FILE_ARGOCD }}"
  ARGOCD_CONF_DIR: "${{ inputs.ARGOCD_CONF_DIR }}"
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  ARGOCD_CLI_VERSION: 2.3.3
  DOCKER_TAG_SUFFIX: "${{ inputs.DOCKER_TAG_SUFFIX }}"
  DEPLOY_TYPE: "${{ inputs.DEPLOY_TYPE }}"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: actions/checkout@v2
      - name: Get Short SHA
        id: sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: argocd login
        uses: clowdhaus/argo-cd-action/@v1.9.0
        with:
          version: ${{ env.ARGOCD_CLI_VERSION }}
          command: login
          options: --insecure --grpc-web --username ${{ secrets.ARGOCD_USER }} --password ${{ secrets.ARGOCD_PASS}} ${{ secrets.ARGOCD_URL }}
     
      - uses: clowdhaus/argo-cd-action/@v1.9.0
        name: add argocd project
        with:
          version: ${{ env.ARGOCD_CLI_VERSION }}
          command: proj
          options: create -f ${{ env.ARGOCD_CONF_DIR }}/${{ env.APP_PROJ_FILE_ARGOCD }} --upsert

      - uses: clowdhaus/argo-cd-action/@v1.9.0
        name: add argocd app
        with:
          version: ${{ env.ARGOCD_CLI_VERSION }}
          command: app
          options: create -f ${{ env.ARGOCD_CONF_DIR }}/${{ env.APP_ENV }}/${{ env.APP_FILE_ARGOCD }} --upsert      

      - name: ArgoCD Overwrite Image Tag
        if: ${{ env.DEPLOY_TYPE == 'kustomize' }}
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: ${{ env.ARGOCD_CLI_VERSION }}
          command: app set ${{ env.APP_NAME }}-${{ env.APP_ENV }}
          options: --kustomize-image "ghcr.io/${{ github.repository }}:${{ steps.sha.outputs.sha8 }}${{ env.DOCKER_TAG_SUFFIX }}"

      - name: Sync ${{ env.APP_ENV }}
        uses: clowdhaus/argo-cd-action/@v1.12.1
        with:
          command: app sync ${{ env.APP_NAME }}-${{ env.APP_ENV }} --prune

      - name: Deploy ${{ env.APP_NAME }} ${{ env.APP_ENV }} version ${{ steps.sha.outputs.sha8 }} by user ${{ github.actor }}
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "${{ env.ALERTS_CHANNEL }}"
